### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by alekksander** [ray-lothian/Send_To#6]
thanks for the addon, unfortunately it doesn't work propely. when video is send to mplayer i got:

`Error: spawn mplayer ENOENT
at exports._errnoException (util.js:1018:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
at onErrorNT (internal/child_process.js:367:16)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9) `

**Comment by alekksander** [comment]
it had to be an issue with my applications. put 'smplayer' in custom command field and works fine now. 

i think You could add smplayer as supported one now ;)
